UPDATE engagements
SET state = CASE state
    WHEN 'DRAFT' THEN 'QUALIFYING'
    WHEN 'LEAD_SELECTED' THEN 'CLIENT_INTELLIGENCE'
    WHEN 'RESEARCH_COMPLETED' THEN 'HYPOTHESIS_READY'
    WHEN 'OUTREACH_IN_PROGRESS' THEN 'OUTREACHING'
    WHEN 'OUTREACH_FAILED' THEN 'OUTREACHING'
    WHEN 'PREPARATION_COMPLETED' THEN 'PREPARING'
    WHEN 'MEETING_IN_PROGRESS' THEN 'IN_MEETING'
    WHEN 'MEETING_COMPLETED' THEN 'DISCOVERY_COMPLETE'
    WHEN 'CONTRACT_WON' THEN 'CLIENT_DECISION'
    WHEN 'CONTRACT_LOST' THEN 'CLIENT_DECISION'
    WHEN 'REVIEW_AVAILABLE' THEN 'REVIEW'
    WHEN 'ARCHIVED' THEN 'COMPLETED'
    ELSE state
END
WHERE state IN (
    'DRAFT',
    'LEAD_SELECTED',
    'RESEARCH_COMPLETED',
    'OUTREACH_IN_PROGRESS',
    'OUTREACH_FAILED',
    'PREPARATION_COMPLETED',
    'MEETING_IN_PROGRESS',
    'MEETING_COMPLETED',
    'CONTRACT_WON',
    'CONTRACT_LOST',
    'REVIEW_AVAILABLE',
    'ARCHIVED'
);

UPDATE engagement_events
SET state = CASE state
    WHEN 'DRAFT' THEN 'QUALIFYING'
    WHEN 'LEAD_SELECTED' THEN 'CLIENT_INTELLIGENCE'
    WHEN 'RESEARCH_COMPLETED' THEN 'HYPOTHESIS_READY'
    WHEN 'OUTREACH_IN_PROGRESS' THEN 'OUTREACHING'
    WHEN 'OUTREACH_FAILED' THEN 'OUTREACHING'
    WHEN 'PREPARATION_COMPLETED' THEN 'PREPARING'
    WHEN 'MEETING_IN_PROGRESS' THEN 'IN_MEETING'
    WHEN 'MEETING_COMPLETED' THEN 'DISCOVERY_COMPLETE'
    WHEN 'CONTRACT_WON' THEN 'CLIENT_DECISION'
    WHEN 'CONTRACT_LOST' THEN 'CLIENT_DECISION'
    WHEN 'REVIEW_AVAILABLE' THEN 'REVIEW'
    WHEN 'ARCHIVED' THEN 'COMPLETED'
    ELSE state
END
WHERE state IN (
    'DRAFT',
    'LEAD_SELECTED',
    'RESEARCH_COMPLETED',
    'OUTREACH_IN_PROGRESS',
    'OUTREACH_FAILED',
    'PREPARATION_COMPLETED',
    'MEETING_IN_PROGRESS',
    'MEETING_COMPLETED',
    'CONTRACT_WON',
    'CONTRACT_LOST',
    'REVIEW_AVAILABLE',
    'ARCHIVED'
);
