-- V33 intentionally generated a large catalogue quickly, but its first-pass
-- descriptions were too thin to support realistic document-based research.
-- This migration enriches only that generated catalogue; author-created
-- scenarios remain fully owned by their authors.
CREATE TEMP TABLE v45_problem_profiles (
    industry TEXT PRIMARY KEY,
    business_situation TEXT NOT NULL,
    observable_symptom TEXT NOT NULL,
    consulting_mandate TEXT NOT NULL,
    unknowns TEXT NOT NULL,
    lead_description TEXT NOT NULL,
    executive_signal TEXT NOT NULL,
    operating_signal TEXT NOT NULL,
    delivery_constraint TEXT NOT NULL,
    decision_question TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO v45_problem_profiles VALUES
('Aerospace & Aviation', 'Fleet availability is under executive review as operations seek to protect dispatch reliability without disrupting maintenance activity.', 'Maintenance, telemetry and engineering records do not yet give operations a consistent view of emerging aircraft issues before dispatch decisions are made.', 'Establish where maintenance-information hand-offs slow reliability decisions and agree a contained pilot that improves early-warning visibility.', 'Which asset group experiences the most avoidable disruption|Who owns the dispatch-versus-maintenance trade-off|Which reliability measure is credible enough for a pilot', 'An aviation operator reviewing predictive-maintenance controls across maintenance, telemetry and engineering records.', 'Dispatch reliability is being reviewed by operations leadership.', 'Teams need earlier visibility of maintenance issues that may affect dispatch.', 'Maintenance, telemetry and engineering records are handled across separate workflows.', 'What small asset-group pilot would demonstrate a reliability improvement without affecting airworthiness controls'),
('Energy & Utilities', 'Grid operations are tightening resilience expectations while field teams need to coordinate response activity across a distributed network.', 'Outage response information is fragmented between GIS, work management and mobile workforce tools, limiting a shared view of field progress.', 'Identify the coordination hand-offs that delay outage response and validate a low-risk way to improve field visibility.', 'Which outage stage creates the longest coordination delay|Which teams control the operational data|How response reliability should be measured', 'A utility evaluating field-response coordination across grid, work-management and mobile-workforce systems.', 'Reliability targets are tightening for grid operations.', 'Field progress is not consistently visible during response activity.', 'GIS, work management and mobile workforce tools are not joined into one operational view.', 'Which response workflow can be improved first without disrupting field crews'),
('Public Sector', 'Service leaders are under scrutiny to make citizen case handling more predictable while retaining accountability across existing public-service workflows.', 'Citizens experience inconsistent triage and follow-up because case information moves between legacy CRM and workflow services.', 'Locate the case-management constraints affecting service timeliness and define a measurable improvement path that preserves public accountability.', 'Which request types wait longest|Which service owner can validate the baseline|What controls cannot be changed during a pilot', 'A public-service organisation examining case-management and service-request triage across legacy CRM and workflow services.', 'A service standards review has been announced.', 'Request triage and follow-up are inconsistent across existing workflows.', 'Legacy CRM and workflow services carry the current case record.', 'Which citizen journey should be used to test a safer, measurable improvement'),
('Real Estate & Construction', 'A capital programme is approaching a gateway review and leadership needs confidence that delivery information is consistent across the portfolio.', 'Cost, schedule and contractor reporting does not provide a timely shared view of milestone risk before funding decisions are made.', 'Clarify the reporting hand-offs that obscure delivery risk and agree a controlled assurance pilot for a priority programme area.', 'Which milestones drive the next funding decision|Which contractor data is trusted|How schedule and cost risk should be reconciled', 'A property-development organisation reviewing portfolio delivery assurance across cost, schedule and contractor reporting.', 'A major project gateway review is approaching.', 'Milestone slippage can affect the release of funding.', 'Cost, schedule and contractor information is reported through separate channels.', 'Which programme gate would benefit from a single, validated delivery view'),
('Media & Entertainment', 'A streaming relaunch is increasing pressure to turn audience and content-operating signals into decisions that protect subscriber experience.', 'Rights, content-supply-chain and analytics information is not yet aligned enough to explain where operational friction is affecting audience outcomes.', 'Determine which content-operating decisions need a better shared view and validate a bounded improvement that supports the relaunch.', 'Which audience outcome is most exposed|Who owns the rights-to-release hand-off|Which signal can be baselined before the relaunch', 'A media organisation preparing a streaming-platform relaunch across rights, content-supply-chain and analytics platforms.', 'Subscription retention is under pressure during the relaunch.', 'Audience and content-operating signals are not consistently connected.', 'Rights, content supply chain and analytics teams rely on different operational views.', 'Which release decision should be piloted to protect subscriber experience'),
('Hospitality & Travel', 'Horizon Hotels is pursuing a brand-experience initiative while property leaders need to deliver a consistent guest service experience across the network.', 'Guest satisfaction varies across properties, indicating that service issues are not being identified and resolved consistently at property level.', 'Discover the operational hand-offs behind service variation and agree a low-risk way to improve consistency without disrupting live guest operations.', 'Which guest journey has the largest variation|Which property teams own the response|Which service measure should establish the baseline', 'A hotel group examining property-service consistency across property-management, service-desk and guest-analytics systems.', 'The brand-experience initiative depends on more consistent guest service.', 'Guest satisfaction varies across properties.', 'Property-management, service-desk and guest-analytics systems are not yet a single operating view.', 'Which guest journey and property cohort should be used for a contained consistency pilot'),
('Education', 'Student-experience leaders are pursuing a retention programme while support teams work across separate enrolment, learning and service workflows.', 'The first-year retention target was missed, but the points at which students lose momentum are not yet visible across the support journey.', 'Identify the support hand-offs that affect first-year continuity and validate an intervention that can be measured without changing academic policy.', 'Which student cohort needs attention first|Which support interaction is least visible|Which outcome can be measured in the next term', 'An education provider redesigning the enrolment and student-support journey across student-information and learning systems.', 'First-year retention is below the intended target.', 'Student support activity is fragmented across the learner journey.', 'Student-information and learning systems hold different parts of the support record.', 'Which first-year support journey can be improved and measured first'),
('Water & Environment', 'Asset leaders are prioritising climate resilience and need a dependable view of inspection and leak-response activity across the network.', 'Non-revenue water is rising while sensor, asset and field-service information does not consistently show where response delays occur.', 'Establish the operational constraints behind leak-response visibility and agree a pilot that improves prioritisation without changing critical field controls.', 'Which asset zone has the weakest response visibility|Who validates inspection priorities|Which measure demonstrates a faster response', 'A water utility examining inspection planning and leak-response visibility across sensor, asset and field-service platforms.', 'Climate-resilience investment is focusing attention on network reliability.', 'Non-revenue water is rising.', 'Sensor, asset and field-service information is not consistently joined for response planning.', 'Which asset zone can provide a controlled leak-response visibility pilot'),
('Food & Agriculture', 'Supply-chain leaders face an export compliance deadline and need traceable evidence across suppliers, warehouses and quality teams.', 'Traceability evidence is required for export, but ERP, warehouse and traceability systems do not provide a consistent end-to-end record.', 'Identify the evidence hand-offs that create compliance risk and validate a scoped improvement for a priority export flow.', 'Which export flow is most exposed|Which supplier record is authoritative|What compliance evidence must be available at release', 'A food cooperative strengthening cold-chain traceability across ERP, warehouse and traceability systems.', 'An export-compliance deadline is approaching.', 'Required traceability evidence is difficult to assemble consistently.', 'Supplier, warehouse and traceability records sit in separate systems.', 'Which priority export flow should be used to prove a complete traceability record'),
('Healthcare', 'Care-access leaders are pursuing a patient-access improvement plan while clinics balance scheduling capacity, referrals and continuity of care.', 'Patient wait times are increasing, but the scheduling and referral hand-offs causing delay are not consistently visible.', 'Clarify the access constraints that extend waits and agree a measurable improvement that protects clinical safety and capacity.', 'Which referral or appointment pathway has the longest delay|Which clinical constraints are non-negotiable|Which access measure will be tracked', 'A clinic network optimising patient access across EHR, scheduling and referral systems.', 'The care-access improvement plan is focused on patient experience.', 'Patient wait times are increasing.', 'EHR, scheduling and referral systems hold different views of the patient journey.', 'Which patient pathway can be improved without compromising clinical safeguards'),
('Industrial Manufacturing', 'Plant leadership is pursuing performance improvement while production teams need faster visibility of exceptions that affect quality and downtime.', 'Unplanned downtime is above target, and MES, ERP and machine data do not consistently reveal the operational sequence behind recurring exceptions.', 'Identify the exception-management hand-offs affecting uptime and agree a controlled improvement around a priority production area.', 'Which production area has the highest repeat disruption|Who owns the exception response|Which uptime and quality measures should be baselined', 'A manufacturer reviewing production-exception management across MES, ERP and machine-data environments.', 'Plant-performance improvement is an executive priority.', 'Unplanned downtime is above target.', 'MES, ERP and machine data are not consistently connected during exception response.', 'Which production area can demonstrate an uptime improvement first'),
('Financial Services', 'Risk operations is working through a remediation plan while onboarding teams must maintain control and customer experience across regulated workflows.', 'Board-tracked remediation milestones are at risk because KYC hand-offs across core banking and digital channels are not consistently transparent.', 'Locate the onboarding-control constraints affecting remediation progress and validate a measured improvement that preserves compliance.', 'Which KYC hand-off causes the largest delay|Which control owner approves change|Which remediation measure is board-relevant', 'A retail bank improving customer-onboarding controls across core-banking and digital-channel services.', 'A risk-remediation plan is being monitored by the board.', 'KYC remediation milestones are at risk.', 'Core-banking and digital-channel services split the onboarding workflow.', 'Which onboarding hand-off can be improved while preserving the required controls'),
('Transport & Logistics', 'Network operations is preparing for peak demand while contract renewal conversations increase the cost of service-reliability failures.', 'Last-mile capacity and delivery signals are not consistently connected across telematics, route and warehouse platforms.', 'Identify the planning constraints behind unreliable last-mile decisions and agree a contained pilot that improves service predictability.', 'Which route or delivery cohort is most exposed|Who owns capacity decisions|Which service measure influences renewal conversations', 'A logistics provider improving last-mile delivery control across telematics, route and warehouse platforms.', 'Peak-season readiness is increasing network pressure.', 'Service reliability is affecting contract renewals.', 'Telematics, route and warehouse platforms do not share one capacity view.', 'Which delivery cohort can validate a low-risk capacity-planning pilot'),
('Professional Services', 'Practice leaders are pursuing a client-service transformation while teams need to balance matter intake, knowledge access and staffing decisions.', 'Utilisation and response time vary by team because practice-management and knowledge systems do not consistently support intake and assignment decisions.', 'Find the matter-intake constraints behind inconsistent client response and agree a measurable, low-disruption improvement for a priority team.', 'Which matter type has the highest response variation|Who controls staffing allocation|Which client-service measure should be baselined', 'A professional-services firm improving matter intake and knowledge-and-staffing coordination.', 'Client-service transformation is a leadership priority.', 'Utilisation and response time vary by team.', 'Practice-management and knowledge systems do not consistently support intake decisions.', 'Which team and matter type should validate a service-consistency pilot'),
('Telecommunications', 'Network-delivery leaders are assuring a commercially committed 5G rollout while coordination failures can put delivery dates at risk.', 'OSS, workforce and network-assurance tools do not consistently expose the dependencies affecting rollout progress and incident triage.', 'Identify the rollout-coordination constraints that threaten committed dates and validate a controlled visibility improvement.', 'Which rollout dependency is least visible|Who owns the delivery decision|Which milestone should be used as the baseline', 'A telecom provider improving rollout coordination and incident triage across OSS, workforce and network-assurance tools.', '5G rollout assurance is tied to commercially committed dates.', 'Rollout dates are at risk when coordination gaps remain unresolved.', 'OSS, workforce and network-assurance tools expose different parts of delivery progress.', 'Which rollout milestone can be used for a constrained assurance pilot'),
('Life Sciences', 'Clinical-operations leaders are accelerating a trial portfolio while sites need dependable visibility of supply, quality and protocol activity.', 'Protocol timelines are at risk because quality, clinical and supply platforms do not consistently show where site-readiness constraints are accumulating.', 'Clarify the cross-functional hand-offs affecting trial-site visibility and validate an improvement that preserves quality controls.', 'Which site-readiness step delays the portfolio|Which quality control must remain intact|Which timeline measure can be tracked', 'A life-sciences organisation improving clinical-supply planning and trial-site visibility across quality, clinical and supply platforms.', 'Trial acceleration is a portfolio priority.', 'Protocol timelines are at risk.', 'Quality, clinical and supply platforms do not consistently expose site-readiness constraints.', 'Which trial-site process can be improved without weakening quality controls'),
('Insurance', 'Claims leaders are pursuing a transformation programme while protecting customer outcomes, control discipline and operational continuity.', 'Cycle time and leakage are under review because policy, claims and document systems do not consistently support straight-through claims decisions.', 'Identify the claims hand-offs that create avoidable delay or leakage and validate a measured improvement for a contained claim segment.', 'Which claim segment has the clearest repeat friction|Which controls govern straight-through processing|Which cycle-time and leakage measures are trusted', 'An insurer improving straight-through claims processing across policy, claims and document systems.', 'The claims-transformation programme is under leadership review.', 'Cycle time and leakage are under review.', 'Policy, claims and document systems hold different parts of the claims decision.', 'Which claim segment can demonstrate a controlled straight-through-processing improvement'),
('Mining & Resources', 'Operations leaders are protecting production stability while maintenance and shutdown decisions must be made from consistent asset information.', 'Availability loss is reducing output because asset, maintenance and production data does not consistently expose execution and shutdown dependencies.', 'Locate the maintenance-execution constraints affecting availability and validate a safe assurance improvement around a priority asset area.', 'Which asset area drives the highest availability loss|Which shutdown decision is most exposed|Which production measure should be baselined', 'A mining operator improving maintenance execution and shutdown-planning assurance across asset, maintenance and production data.', 'Production stability is a leadership priority.', 'Availability loss is reducing output.', 'Asset, maintenance and production information is fragmented across operational decisions.', 'Which asset area can support a safe availability-assurance pilot'),
('Housing & Community', 'Customer-service leaders are running a service-recovery plan while repairs teams need to make tenant case progress visible and dependable.', 'Repair completion times are escalating because housing-management and communication systems do not consistently show ownership, appointment and completion status.', 'Identify the repairs-case constraints delaying completion and validate a client-safe improvement for a priority repair journey.', 'Which repair type has the longest completion time|Who owns the tenant communication hand-off|Which service measure should be visible daily', 'A social-housing provider improving repairs-case management and tenant-service recovery across housing-management and communications systems.', 'The service-recovery plan is focused on tenant experience.', 'Repair completion times are escalating.', 'Housing-management and communication systems do not provide one clear repair-status view.', 'Which repair journey can be improved first while protecting tenant communication'),
('Consumer Products', 'Commercial leaders are protecting margin while demand-planning and trade-promotion decisions need a shared view of forecast and distributor signals.', 'Forecast error is eroding margin because planning, distributor and CRM data does not consistently show the assumptions behind promotion and demand decisions.', 'Clarify the demand-planning constraints affecting margin and validate a bounded improvement for a priority category or promotion cycle.', 'Which category has the greatest forecast variation|Who owns the promotion assumption|Which margin measure can be traced to the decision', 'A consumer-goods company improving demand planning and trade-promotion execution across planning, distributor and CRM data.', 'Margin protection is a commercial priority.', 'Forecast error is eroding margin.', 'Planning, distributor and CRM data expose different demand and promotion assumptions.', 'Which category or promotion cycle can test a more reliable planning view'),
('Automotive', 'Customer-experience leaders are pursuing after-sales growth while dealer teams need a consistent view of connected service and warranty activity.', 'Service retention is declining because dealer, warranty and customer data does not consistently expose the customer journey or follow-up ownership.', 'Identify the service-operating hand-offs affecting retention and validate a low-risk improvement for a priority dealer cohort.', 'Which service journey has the largest retention drop|Who owns dealer follow-up|Which retention measure should establish the baseline', 'An automotive group improving dealer-service operations and connected service experience across dealer, warranty and customer data.', 'After-sales growth depends on a stronger service experience.', 'Service retention is declining.', 'Dealer, warranty and customer data do not provide one view of the service journey.', 'Which dealer cohort can validate a connected-service improvement first'),
('Technology', 'Customer-delivery leaders are scaling enterprise onboarding while implementation and support teams protect existing renewal commitments.', 'Implementation backlog is affecting renewals because delivery, support and product-telemetry information does not consistently expose onboarding risk and ownership.', 'Locate the delivery constraints behind backlog and validate a controlled improvement for a priority enterprise onboarding flow.', 'Which onboarding stage creates the largest backlog|Who owns the renewal-risk decision|Which delivery measure should be baselined', 'A technology provider accelerating enterprise customer onboarding across delivery, support and product-telemetry systems.', 'Enterprise scale-up is increasing delivery pressure.', 'Implementation backlog is affecting renewals.', 'Delivery, support and product telemetry do not provide one view of onboarding risk.', 'Which enterprise onboarding flow can prove a measurable backlog reduction'),
('Government', 'Service-delivery leaders are responding to an improvement review while grant teams must retain transparency and control across public casework.', 'Audit findings require a measurable response because case-management, records and payments platforms do not consistently show grant-workflow status and accountability.', 'Identify the transparency constraints behind the findings and validate an improvement that protects public accountability.', 'Which grant workflow lacks visibility|Which control owner validates the response|Which audit-relevant measure should be tracked', 'A government agency improving grant administration and casework transparency across case-management, records and payments platforms.', 'A public-value improvement review is under way.', 'Audit findings require a measurable response.', 'Case-management, records and payments platforms expose different parts of grant progress.', 'Which grant workflow can establish a transparent, controlled improvement'),
('Nonprofit & Social Impact', 'Programme leaders are approaching a funding-renewal cycle while teams need a credible view of activity, outcomes and evidence across programmes.', 'Funders need clearer impact evidence because CRM, grants and impact-measurement tools do not consistently connect programme activity to reported outcomes.', 'Clarify the reporting constraints affecting funding confidence and validate a practical improvement for a priority programme outcome.', 'Which outcome needs stronger evidence|Who owns the programme data|Which reporting measure will matter in the renewal conversation', 'A nonprofit improving programme-impact reporting and funding-outcome visibility across CRM, grants and impact-measurement tools.', 'The funding-renewal cycle is approaching.', 'Funders need clearer impact evidence.', 'CRM, grants and impact-measurement tools do not consistently connect activity to outcome evidence.', 'Which programme outcome can demonstrate a more credible evidence trail first');

UPDATE scenarios s
SET business_situation = p.business_situation,
    observable_symptom = p.observable_symptom,
    consulting_mandate = p.consulting_mandate,
    unknowns_to_validate = p.unknowns,
    updated_at = NOW(),
    version = version + 1
FROM v45_problem_profiles p
WHERE s.industry = p.industry
  AND s.id::text LIKE '62000000-0000-0000-0000-%';

UPDATE leads l
SET public_description = p.lead_description,
    pain_severity = p.operating_signal,
    updated_at = NOW(),
    version = l.version + 1
FROM scenarios s
JOIN v45_problem_profiles p ON p.industry = s.industry
WHERE l.scenario_id = s.id
  AND s.id::text LIKE '62000000-0000-0000-0000-%';

WITH ranked_signals AS (
    SELECT ls.id, ls.lead_id, p.executive_signal, p.operating_signal,
           row_number() OVER (PARTITION BY ls.lead_id ORDER BY ls.id) AS signal_position
    FROM lead_signals ls
    JOIN leads l ON l.id = ls.lead_id
    JOIN scenarios s ON s.id = l.scenario_id
    JOIN v45_problem_profiles p ON p.industry = s.industry
    WHERE s.id::text LIKE '62000000-0000-0000-0000-%'
)
UPDATE lead_signals ls
SET label = CASE WHEN r.signal_position = 1 THEN r.executive_signal ELSE r.operating_signal END,
    category = CASE WHEN r.signal_position = 1 THEN 'EXECUTIVE_PRIORITY' ELSE 'OPERATING_SIGNAL' END
FROM ranked_signals r
WHERE ls.id = r.id
  AND r.signal_position <= 2;

INSERT INTO lead_signals (id, lead_id, label, category)
SELECT (
           substr(md5('v45:' || l.id::text || ':constraint'), 1, 8) || '-' ||
           substr(md5('v45:' || l.id::text || ':constraint'), 9, 4) || '-' ||
           substr(md5('v45:' || l.id::text || ':constraint'), 13, 4) || '-' ||
           substr(md5('v45:' || l.id::text || ':constraint'), 17, 4) || '-' ||
           substr(md5('v45:' || l.id::text || ':constraint'), 21, 12)
       )::uuid,
       l.id,
       p.delivery_constraint,
       'DELIVERY_CONSTRAINT'
FROM leads l
JOIN scenarios s ON s.id = l.scenario_id
JOIN v45_problem_profiles p ON p.industry = s.industry
WHERE s.id::text LIKE '62000000-0000-0000-0000-%'
ON CONFLICT (id) DO NOTHING;

INSERT INTO lead_signals (id, lead_id, label, category)
SELECT (
           substr(md5('v45:' || l.id::text || ':decision'), 1, 8) || '-' ||
           substr(md5('v45:' || l.id::text || ':decision'), 9, 4) || '-' ||
           substr(md5('v45:' || l.id::text || ':decision'), 13, 4) || '-' ||
           substr(md5('v45:' || l.id::text || ':decision'), 17, 4) || '-' ||
           substr(md5('v45:' || l.id::text || ':decision'), 21, 12)
       )::uuid,
       l.id,
       p.decision_question,
       'DECISION_QUESTION'
FROM leads l
JOIN scenarios s ON s.id = l.scenario_id
JOIN v45_problem_profiles p ON p.industry = s.industry
WHERE s.id::text LIKE '62000000-0000-0000-0000-%'
ON CONFLICT (id) DO NOTHING;
